apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
spec:
  selector:
    matchLabels:
      app: go-api
  replicas: 1
  template:
    metadata:
      labels:
        app: go-api
    spec:
      imagePullSecrets:
        - name: harbour
      containers:
      - name: go-api
        image: registry.us.linkeye.io/india-production/co-pilot-go-api-v1
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: varlog
            mountPath: /app/logs
          - name: env-config-volume
            mountPath: /app/.env 
            subPath: .env # Mount the ConfigMap here
      volumes:
        - name: varlog
          emptyDir: {}
        - name: env-config-volume
          secret:
            secretName: go-api-env  # Reference to the ConfigMap