apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: go-ui
spec:
  selector:
    matchLabels:
      app: go-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: go-ui
    spec:
      # Reference the secret that holds Azure Container Registry credentials
      imagePullSecrets:
        - name: harbour
      containers:
      - name: go-ui
        image: registry.us.linkeye.io/uat/co-pilot-go-ui-v1   #registry.us.linkeye.io/india-production/copilot-v3.5 #linkeye.azurecr.io/stg-linkeye-co-pilot-ui-v3.0       
        
        ports:
        - containerPort: 80