apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: wan-dpu
spec:
  selector:
    matchLabels:
      app: wan-dpu
  replicas: 1
  template:
    metadata:
      labels:
        app: wan-dpu
    spec:
      imagePullSecrets:
        - name: harbour #harbour
      containers:
      - name: wan-dpu
        image: registry.us.linkeye.io/go/wan-env
        # ports:
        # - containerPort: 8080
        # envFrom:
        #     - configMapRef:
        #         name: go-dpu-config-properties
        volumeMounts:
        - name: config-volume
          mountPath: "/Wan/config"
          # subPath: config.properties
          readOnly: true
        - name: env-config-volume
          mountPath: "/Wan/env"
        - name: varlog
          mountPath: /Wan/logs  
          # subPath: .env
        - name: tls-cert
          mountPath: /usr/local/kafka/ssl/ca.crt
          subPath: tls.crt
          readOnly: true
        - name: tls-cert
          mountPath: /usr/local/kafka/ssl/client.crt
          subPath: tls.crt
          readOnly: true
        - name: tls-cert
          mountPath: /usr/local/kafka/ssl/client.key
          subPath: tls.key
          readOnly: true

      - name: vector
        image: timberio/vector:latest-alpine
        volumeMounts:
          - name: varlog
            mountPath: /Wan/logs
          - name: vector-config
            mountPath: /etc/vector
        env:
          - name: VECTOR_CONFIG
            value: /etc/vector/vector.toml    

      volumes:
      - name: config-volume
        configMap:
          name: go-dpu-config-properties
      - name: env-config-volume
        secret:
          secretName: go-dpu-secrets
      - name: tls-cert
        secret:
          secretName: kafka-tls-stg
      # - name: tls-key
      #   secret:
      #     secretName: client-key-secret   
      # - name: tls-crt
      #   secret:
      #     secretName: client-crt-secret    
      - name: varlog
        emptyDir: {}    
      - name: vector-config
        configMap:
          name: wan-vector-config     